YouWatchASP/Areas/Administration/Controllers/ActorsAdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YouWatchASP.Areas.Administration.Models.ActorsAdminViewModels;
using YouWatchASP.Areas.Utils;
using YouWatchASP.Services.Data.Contracts;

namespace YouWatchASP.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    [Route("[area]/[controller]/[action]")]
    public class ActorsAdminController : Controller
    {
        private readonly IActorService _actorService;
        private readonly IMapper _mapper;

        public ActorsAdminController(IActorService actorService, IMapper mapper)
        {
            _actorService = actorService ?? throw new ArgumentNullException(nameof(actorService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> Index(
            string sortOrder,
            string searchString,
            string currentFilter,
            int? pageNumber
            )
        {

            ViewData["FirstNameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "FirstName_Desc" : "";
            ViewData["LastNameSortParam"] = String.IsNullOrEmpty(sortOrder) ? "LastName_Desc" : "";
            ViewData["OscarsSortParam"] = String.IsNullOrEmpty(sortOrder) ? "Oscars_Desc" : "";
            ViewData["ModifiedDateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "ModifiedDate_Desc" : "ModifiedDate";
            ViewData["CreatedDateSortParam"] = sortOrder == "CreatedDate" ? "CreatedDate_Desc" : "CreatedDate";
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var actors = await _actorService.GetListOfActorsAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                actors = actors.Where(a => a.FirstName.ToLower().Contains(searchString.ToLower())
                                       || a.LastName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "FirstName_Desc":
                    actors = actors.OrderByDescending(a => a.FirstName).ToList();
                    break;
                case "LastName_Desc":
                    actors = actors.OrderByDescending(a => a.LastName).ToList();
                    break;
                case "Oscars_Desc":
                    actors = actors.OrderByDescending(a => a.Oscars).ToList();
                    break;
                case "CreatedDate":
                    actors = actors.OrderBy(a => a.CreatedOn).ToList();
                    break;
                case "CreatedDate_Desc":
                    actors = actors.OrderByDescending(a => a.CreatedOn).ToList();
                    break;
                case "ModifiedDate":
                    actors = actors.OrderBy(a => a.ModifiedOn).ToList();
                    break;
                case "ModifiedDate_Desc":
                    actors = actors.OrderByDescending(a => a.ModifiedOn).ToList();
                    break;
                default:
                    actors = actors.OrderBy(a => a.FirstName)
                        .ThenBy(a => a.LastName).ToList();
                    break;
            }

            IEnumerable<ActorAdminViewModel> vm = actors.Select(_mapper.Map<ActorAdminViewModel>).ToList();

            int pageSize = 7;   

            return View(await PaginatedList<ActorAdminViewModel>.CreateAsync(vm, pageNumber ?? 1, pageSize));
        }


    }
}

YouWatchASP/Areas/Administration/Views/ActorsAdmin/Index.cshtml
@model PaginatedList<ActorAdminViewModel>
@{
    ViewData["Title"] = "Index";
}
<section class="module">
    <div class="container">
        <h2>All Actors</h2>
        <p>
            <a asp-area="Administration" asp-controller="WorkInProgress" asp-action="Index" class="btn btn-default">Create New</a>
        </p>
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p>
                    Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-default" /> |
                    <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index">Back to Full List</a>
                </p>
            </div>
        </form>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["FirstNameSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">First Name</a>
                    </th>
                    <th>
                        <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["LastNameSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Last Name</a>
                    </th>
                    <th>
                        <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["OscarsSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Oscars</a>
                    </th>
                    <th>
                        <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["CreatedDateSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Created On</a>
                    </th>
                    <th>
                        <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index" asp-route-sortOrder="@ViewData["ModifiedDateSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Modified On</a>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Oscars)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedOn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ModifiedOn)
                        </td>
                        <td>
                            <a asp-area="Administration" asp-controller="WorkInProgress" asp-action="Index">Edit</a> |
                            <a asp-area="Administration" asp-controller="WorkInProgress" asp-action="Index">Details</a> |
                            <a asp-area="Administration" asp-controller="WorkInProgress" asp-action="Index">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-area="Administration"
           asp-controller="ActorsAdmin"
           asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            <<
        </a>
        <a asp-area="Administration"
           asp-controller="ActorsAdmin"
           asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            >>
        </a>

    </div>
</section>