YouWatchASP/Controllers/ActorsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YouWatchASP.Data.Models;
using YouWatchASP.Data.Models.Exceptions;
using YouWatchASP.Models;
using YouWatchASP.Services.Data.Contracts;

namespace YouWatchASP.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class ActorsController : Controller
    {
        private readonly IActorService _actorService;
        private readonly IMapper _mapper;
        private readonly IMovieService _movieService;
        private readonly IMemoryCache _cache;
        private const string ActorsCacheKey = "actors";

            public ActorsController(IActorService actorService, IMapper mapper, IMovieService movieService, IMemoryCache cache)
        {
            _actorService = actorService ?? throw new ArgumentNullException(nameof(actorService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _movieService = movieService ?? throw new ArgumentNullException(nameof(movieService));
            _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString)
        {
            ICollection<ActorViewModel> cachedActors;

            if(!_cache.TryGetValue(ActorsCacheKey, out cachedActors))
            {

                ICollection<Actor> actors = await _actorService.GetListOfActorsAsync();
                var orderedActors = actors.OrderBy(a => a.FirstName)
                        .ThenBy(a => a.LastName);
                cachedActors = orderedActors.Select(_mapper.Map<ActorViewModel>).ToList();

                var cacheEntryOptions = new MemoryCacheEntryOptions()
                                        .SetSlidingExpiration(TimeSpan.FromSeconds(60));

                _cache.Set(ActorsCacheKey, cachedActors, cacheEntryOptions);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                cachedActors = cachedActors.Where(a => a.FirstName.ToLower().Contains(searchString.ToLower())
                               || a.LastName.ToLower().Contains(searchString.ToLower())).ToList();
                cachedActors = cachedActors.Select(_mapper.Map<ActorViewModel>).ToList();
            }

            return View(cachedActors);


        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            ActorViewModel cachedActor;

            try
            {
                var singleActorKey = ActorsCacheKey + id.ToString();

                if (!_cache.TryGetValue(singleActorKey, out cachedActor))
                {
                    var actor = await _actorService.GetActorAsync(id);
                    cachedActor = _mapper.Map<ActorViewModel>(actor);

                    var cacheEntryOptions = new MemoryCacheEntryOptions()
                                        .SetSlidingExpiration(TimeSpan.FromSeconds(60));

                    _cache.Set(singleActorKey, cachedActor, cacheEntryOptions);
                }

                return View(cachedActor);
            }
            catch (ActorNotFoundException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Remove(ActorViewModel model)
        {
            try
            {
                var actor = await _actorService.RemoveAsync(model.Id);

                TempData["SuccessRemoved"] = $"{actor.FirstName} {actor.LastName} has been successfully removed from the database.";
                return RedirectToAction(nameof(Index));
            }
            catch(ActorNotFoundException)
            {
                return NotFound();
            }
            catch (ArgumentException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var actor = await _actorService.GetActorAsync(id);

                var actorViewModel = _mapper.Map<ActorViewModel>(actor);

                return View(actorViewModel);
            }
            catch(ActorNotFoundException)
            {
                return NotFound();
            }
            catch(ArgumentException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return View(id);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ActorViewModel actorViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(actorViewModel);
            }

            try
            {
                var actor = await _actorService.EditAsync(actorViewModel.Id,
                    actorViewModel.FirstName, actorViewModel.LastName, actorViewModel.Oscars, actorViewModel.ImageUrl);

                TempData["Success"] = "Actor successfully updated.";
                return RedirectToAction(nameof(Details), new { id = actor.Id });
            }
            catch (ActorNotFoundException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ActorViewModel actorViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(actorViewModel);
            }

            try
            {
                var actor = await _actorService.CreateAsync(
                    actorViewModel.FirstName, actorViewModel.LastName, actorViewModel.Oscars, actorViewModel.ImageUrl);
                return RedirectToAction(nameof(Details), new { id = actor.Id });

            }
            catch (ArgumentException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                TempData["Error"] = "Actor with that name already exists.";
                return View(actorViewModel);
            }

        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AddMovie(int id)
        {
            var actor = await _actorService.GetActorAsync(id);

            var actorMovieViewModel = _mapper.Map<ActorMovieViewModel>(actor);

            var allMovies = await _movieService.GetAllMovie();

            var availableMovies = allMovies.Except(actor.ActorMovie.Select(x => x.Movie)).ToList();

            actorMovieViewModel.AvailableMovies = availableMovies.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();

            return View(actorMovieViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMovie(ActorMovieViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var actor = await _actorService.AddMovieAsync(model.ActorId, model.MovieId);
                return RedirectToAction(nameof(Details), new { id = model.ActorId });

            }
            catch (ArgumentException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                TempData["Error"] = "Actor with that name already exists.";
                return View(model);
            }

        }
    }
}

YouWatchASP/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using YouWatchASP.Data.Models;
using YouWatchASP.Data.Models.Exceptions;
using YouWatchASP.Models;
using YouWatchASP.Models.Director;
using YouWatchASP.Services.Data;
using YouWatchASP.Services.Data.Contracts;

namespace YouWatchASP.Controllers
{
    [Authorize(Roles = "Administrator,User")]
    public class DirectorsController : Controller
    {
        private readonly IDirectorService _directorService;
        private readonly IMapper _mapper;
        private readonly IMemoryCache _cache;
        private const string DirectorsCacheKey = "Director";

        public DirectorsController(IDirectorService directorService, IMapper mapper, IMemoryCache cache)
        {
            _directorService = directorService ?? throw new ArgumentNullException(nameof(directorService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        }

        public async Task<IActionResult> Index()
        {
            ICollection<DirectorViewModel> cachedDirectors;

            if(!_cache.TryGetValue(DirectorsCacheKey,out cachedDirectors))
            {
                var directorList = await _directorService.GetListAsync();


                cachedDirectors = directorList.Select(_mapper.Map<DirectorViewModel>)
                                                                .OrderBy(m => m.FirstName).ToList();

                var cacheEntryOptions = new MemoryCacheEntryOptions()
                                        .SetSlidingExpiration(TimeSpan.FromSeconds(60));

                _cache.Set(DirectorsCacheKey, cachedDirectors, cacheEntryOptions);
            }
           
            return View(cachedDirectors);
            
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var director = await _directorService.GetById(id);

            return  View(_mapper.Map<DirectorViewModel>(director));
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (DirectorViewModel directorViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                var director =await  _directorService.CreateAsync(directorViewModel.FirstName, directorViewModel.LastName,
                                                            directorViewModel.Oscars, directorViewModel.ImageUrl);

                return RedirectToAction("Details", new { id = director.Id });
            }
            catch (ArgumentException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                TempData["Error"] = "Director with that name already exists.";
                return View();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var director = await _directorService.GetById(id);

                var directorViewModel = _mapper.Map<DirectorViewModel>(director);

                return View(directorViewModel);
            }
            catch (DirectorNotFoundExeption)
            {
                return NotFound();
            }
            
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DirectorViewModel directorViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return View(directorViewModel);
            }

            try
            {
                var director = await _directorService.EditAsync(directorViewModel.Id,
                    directorViewModel.FirstName, directorViewModel.LastName, directorViewModel.Oscars, directorViewModel.ImageUrl);

                TempData["Success"] = "Actor successfully updated.";
                return RedirectToAction(nameof(Details), new { id = director.Id });
            }
            catch (ActorNotFoundException ex)
            {
                this.ModelState.AddModelError("Error", ex.Message);
                return NotFound();
            }
        }
    }
}

YouWatchASP/Controllers/WorkInProgressAllController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace YouWatchASP.Areas.Administration.Controllers
{
    
    [Authorize(Roles = "Administrator, User")]
    public class WorkInProgressAllController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

YouWatchASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en-US" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--
    Document Title
    =============================================
    -->
    <title>@ViewData["Title"] - YouWatch</title>
    <!--
    Favicons
    =============================================
    -->
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-icon-180x180.png">
    <link rel="icon" type="/image/png" sizes="192x192" href="/images/favicons/android-icon-192x192.png">
    <link rel="icon" type="/image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png">
    <link rel="icon" type="/image/png" sizes="96x96" href="/images/favicons/favicon-96x96.png">
    <link rel="icon" type="/image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/images/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!--
    Stylesheets
    =============================================

    -->
    <!-- Default stylesheets-->
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css">
    <!-- Template specific stylesheets-->
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@



    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Volkhov:400i">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800">
    <link rel="stylesheet" href="/lib/animate.css/animate.css">
    <link rel="stylesheet" href="/lib/components-font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/lib/et-line-font/et-line-font.css">
    <link rel="stylesheet" href="/lib/flexslider/flexslider.css">
    <link rel="stylesheet" href="/lib/owl.carousel/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="/lib/owl.carousel/dist/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="/lib/magnific-popup/dist/magnific-popup.css">
    <link rel="stylesheet" href="/lib/simple-text-rotator/simpletextrotator.css">
    <!-- Main stylesheet and color file-->
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" id="color-scheme" href="/css/colors/default.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">

    <main>
        <div class="page-loader">
            <div>
                <div class="loader">Loading...</div>
            </div>
        </div>
        <nav class="navbar navbar-custom navbar-fixed-top navbar-default" role="navigation">
            <div class="container">
                <div class="dropdown-toggle">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><a asp-controller="Home" asp-action="Index" class="large-text navbar-brand">You Watch</a>
                    <div class="collapse navbar-collapse" id="custom-collapse">
                        <ul class="nav navbar-nav navbar-right ">
                            @if (User.Identity.IsAuthenticated)
                            {
                                @if (User.IsInRole("Administrator"))
                                {
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">Administration</a>
                                        <ul class="dropdown-menu">
                                            <li> <a asp-area="Administration" asp-controller="ActorsAdmin" asp-action="Index">Actors</a></li>
                                        </ul>
                                    </li>
                                }
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Movies</a>
                                    <ul class="dropdown-menu">
                                        @if (User.IsInRole("Administrator"))
                                        {
                                            <li> <a asp-controller="Movies" asp-action="Create">Add Movie</a></li>
                                            <li> <a asp-controller="WorkInProgressAll" asp-action="Index">Remove Movie</a></li>
                                            <li> <a asp-controller="Movies" asp-action="Update">Update Movie</a></li>
                                        }
                                        <li> <a asp-controller="Movies" asp-action="Index">All Movies</a></li>
                                        <li>
                                        <li class="dropdown">
                                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Top 10 By</a>
                                            <ul class="dropdown-menu">
                                                <li class="dropdown">
                                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Genre</a>
                                                    <ul class="dropdown-menu">
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Action</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Adventure</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Animation</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Comedy</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Crime</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Drama</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Fantasy</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Historical</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Horror</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Romance</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Thriller</a></li>
                                                        <li><a asp-controller="WorkInProgressAll" asp-action="Index">Western</a></li>
                                                    </ul>
                                                </li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Oscars</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Rating</a></li>
                                            </ul>
                                        <li class="dropdown">
                                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Search By</a>
                                            <ul class="dropdown-menu">
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Actors</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Director</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Genres</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Key words</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Oscars</a></li>
                                                <li><a asp-controller="WorkInProgressAll" asp-action="Index">Producers</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Actors</a>
                                    <ul class="dropdown-menu">
                                        @if (User.IsInRole("Administrator"))
                                        {
                                            <li><a asp-controller="Actors" asp-action="Create">Add Actor</a></li>
                                        }
                                        <li> <a asp-controller="Actors" asp-action="Index">All Actors</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Directors</a>
                                    <ul class="dropdown-menu">
                                        @*@if (User.IsInRole("Administrator"))
                                            {
                                                <li><a asp-controller="Actors" asp-action="Create">Add Actor</a></li>
                                            }*@
                                        <li> <a asp-controller="Directors" asp-action="Index">All Directors</a></li>
                                        @if (User.IsInRole("Administrator"))
                                        {
                                            <li> <a asp-controller="Directors" asp-action="Create">Add Director</a></li>
                                        }
                                    </ul>
                                </li>
                            }
                            <li class="btn-b">
                            <li>
                                @await Html.PartialAsync("_LoginPartial")
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    </main>
    @RenderBody()

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/wow/dist/wow.js"></script>
    <script src="/lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js"></script>
    <script src="/lib/isotope/dist/isotope.pkgd.js"></script>
    <script src="/lib/imagesloaded/imagesloaded.pkgd.js"></script>
    <script src="/lib/flexslider/jquery.flexslider.js"></script>
    <script src="/lib/owl.carousel/dist/owl.carousel.min.js"></script>
    <script src="/lib/smoothscroll.js"></script>
    <script src="/lib/magnific-popup/dist/jquery.magnific-popup.js"></script>
    <script src="/lib/simple-text-rotator/jquery.simple-text-rotator.min.js"></script>
    <script src="/js/plugins.js"></script>
    <script src="/js/main.js"></script>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

YouWatchASP/Views/Shared/_PaginationViewPartial.cshtml
@model PaginationViewModel
<div class="pagination-holder black clearfix center">
    <ul id="dark-pagination" class="pagination dark-theme simple-pagination">
        @if (Model.HasPreviousPage)
        {
            <li>
                <a asp-area="@Model.AreaRoute" asp-controller="@Model.ControllerRoute" asp-action="@Model.ActionRoute"
                   asp-route-pageNumber="1" asp-route-searchTerm="@(Model.SearchTerm)"
                   asp-route-pageSize="@(Model.PageSize)" asp-route-sortOrder="@Model.SortOrder"
                   method="post" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#tablePartial"
                   class="page-link">First</a>
            </li>
            <li>
                <a asp-area="@Model.AreaRoute" asp-controller="@Model.ControllerRoute" asp-action="@Model.ActionRoute"
                   asp-route-pageNumber="@(Model.PageNumber - 1)" asp-route-searchTerm="@(Model.SearchTerm)"
                   asp-route-pageSize="@(Model.PageSize)" asp-route-sortOrder="@Model.SortOrder"
                   method="post" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#tablePartial"
                   class="page-link">Prev</a>
            </li>
        }
        else
        {
            <li><a class="page-link current">First</a></li>
            <li><a class="page-link current">Prev</a></li>
        }
        @for (int i = (Model.PageNumber <= 5 ? 1 : Model.PageNumber - 5); i <= (Model.PageNumber >= Model.PageCount - 5 ? Model.PageCount : Model.PageNumber + 5); i++)
        {
            if (Model.PageNumber == i)
            {
                <li><a class="page-link current">@i</a></li>
            }
            else
            {
                <li>
                    <a asp-area="@Model.AreaRoute" asp-controller="@Model.ControllerRoute" asp-action="@Model.ActionRoute"
                       asp-route-pageNumber="@i" asp-route-searchTerm="@(Model.SearchTerm)"
                       asp-route-pageSize="@(Model.PageSize)" asp-route-sortOrder="@Model.SortOrder"
                       method="post" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#tablePartial"
                       class="page-link">@i</a>
                </li>
            }
        }
        @if (Model.HasNextPage)
        {
            <li>
                <a asp-area="@Model.AreaRoute" asp-controller="@Model.ControllerRoute" asp-action="@Model.ActionRoute"
                   asp-route-pageNumber="@(Model.PageNumber + 1)" asp-route-searchTerm="@(Model.SearchTerm)"
                   asp-route-pageSize="@(Model.PageSize)" asp-route-sortOrder="@Model.SortOrder"
                   method="post" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#tablePartial"
                   class="page-link">Next</a>
            </li>
            <li>
                <a asp-area="@Model.AreaRoute" asp-controller="@Model.ControllerRoute" asp-action="@Model.ActionRoute"
                   asp-route-pageNumber="@Model.PageCount" asp-route-searchTerm="@(Model.SearchTerm)"
                   asp-route-pageSize="@(Model.PageSize)" asp-route-sortOrder="@Model.SortOrder"
                   method="post" data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" data-ajax-update="#tablePartial"
                   class="page-link">Last</a>
            </li>
        }
        else
        {
            <li><a class="page-link current">Next</a></li>
            <li><a class="page-link current">Last</a></li>
        }
    </ul>
</div>